spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal_exam?serverTimezone=America/Lima&allowPublicKeyRetrieval=false
    password: 12345
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

app:
  secret:
     key: 88fa0d759f845b47c044c2cd44e29082cf6fea665c30c146374ec7c8f3d699e3
  expiration : 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui-exam.html